version: "3.9"

services:
  syokinet:
    image: sav4ner/syokinet
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - syokinet_db
    # command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:5000 syoki.wsgi"

  syokinet_db:
    image: postgres:15.1-alpine
    container_name: syokinet_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
  cache:
    driver: local
