version: "3.4"

services:
  syokinet:
    image: syokinet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: syokinet_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
  cache:
    driver: local
